on:
  push:
    branches:
      - "gh-pages"
  workflow_dispatch:

name: drat-readme

jobs:
  drat-readme:
    name: Update README
    runs-on: ubuntu-20.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0" # Allows corect dates in git history

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - name: update repo indices # needed if tar balls removed manually
        run: |
          install.packages("drat")
          drat::updateRepo(".")
        shell: Rscript {0}

      - name: Drat -- update README.Rmd
        if: success()
        run: |
          install.packages(c('rmarkdown', 'bslib', 'knitr'))
          rmarkdown::render("README.Rmd", output_format = "html_document", output_file = "index.html")
          rmarkdown::render("README.Rmd", output_format = "github_document")
        shell: Rscript {0}

      - name: Commit and push
        if: success()
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "GitHub Actions"
          git commit README.md index.html -m "Update README (auto)" || echo "Nothing to commit"
          git push origin || echo "Nothing to commit"
